apiVersion: v1
kind: Namespace
metadata:
  name: project
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dummy
  name: dummy
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
      - image: czdev/blue
        name: dummy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue
  name: blue
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - image: sgleal97/clientego
        name: blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: servergrpc
  name: servergrpc
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servergrpc
  template:
    metadata:
      labels:
        app: servergrpc
    spec:
      containers:
      - image: sgleal97/grpcgoserver
        name: servergrpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: green
  name: green
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - image: sandraeu/goredispub
        name: green
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: subredis
  name: subredis
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subredis
  template:
    metadata:
      labels:
        app: subredis
    spec:
      containers:
      - image: sandraeu/redissubgo
        name: subredis
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dummy
  name: dummy
  namespace: project
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: dummy
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue
  name: blue
  namespace: project
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: blue
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: servergrpc
  name: servergrpc
  namespace: project
spec:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: servergrpc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: green
  name: green
  namespace: project
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: green
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
  name: dummy-ingress
  namespace: project
spec:
  rules:
    - host: dummy.grupo11.cf
      http:
        paths:
          - backend:
              serviceName: dummy
              servicePort: 5000
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
    ingress.kubernetes.io/rewrite-target: /
  name: blue-ingress
  namespace: project
spec:
  rules:
    - host: blue.grupo11.cf
      http:
        paths:
          - backend:
              serviceName: blue
              servicePort: 5000
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
    ingress.kubernetes.io/rewrite-target: /
  name: green-ingress
  namespace: project
spec:
  rules:
    - host: green.grupo11.cf
      http:
        paths:
          - backend:
              serviceName: green
              servicePort: 5000
---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: function-split
  namespace: project
spec:
  service: dummy
  backends:
  - service: blue
    weight: 500m
  - service: green
    weight: 500m
